# GLOBAL SITE SETTINGS

cname: theweddingwarren.yourwebvisual.com

# META
title: The Wedding Warren
seo_title: The Wedding Warren
company:
description:

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/theweddingwarren.com
github_repo_name:
jekyll_version: 3.0.3

# OFFICES
offices:
  - title: Beachside Dojo
    address: 55 North Steyne<br>Manly NSW

  - title: Novotel Pacific Manly
    address: 55 North Steyne<br> Manly NSW
    phone: (02) 9977 7666
    website: http://www.novotelmanlypacific.com.au

# SOCIAL MEDIA
facebook:
linked_in:
google_plus:
instagram: http://instagram.com/artiqulet

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo.svg
  description: liquidvisual